// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XkdlPoc
{
    internal sealed partial class Vsix
    {
        public const string Id = "XkdlPoc.45ca478e-eb33-40b4-9f71-4c8212073e28";
        public const string Name = "XkdlPoc";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.0.3.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
